export default {
  basePath: "/api",
  FETCH_PLAYBOOKS: "FETCH_PLAYBOOKS",
  FETCH_PLAYBOOK: "FETCH_PLAYBOOK",
  PLAY_PLAYBOOK: "PLAY_PLAYBOOK",
  FETCH_INVENTORIES: "FETCH_INVENTORIES",
  FETCH_CONFIG: "FETCH_CONFIG",
  UPDATE_CONFIG: "UPDATE_CONFIG",
  CATCH_ERROR: "CATCH_ERROR",
  CLOSE_ERROR: "CLOSE_ERROR"
};
